<#
.SYNOPSIS
    This script connects to one or more Nutanix Prism Central instances using the v4 REST API
    to collect unresolved alerts from Prism Element clusters and generate a color-coded HTML report.

.DESCRIPTION
    The script takes a list of Prism Central (PC) IPs or FQDNs as input. It securely prompts
    for credentials, then iterates through each PC to fetch unresolved alerts via the
    /api/monitoring/v4.0/serviceability/alerts endpoint.

    It is filtered to only show alerts originating from a 'cluster' source entity type.

    The output is a single HTML file saved to the user's desktop, with alerts grouped by
    cluster. Rows are color-coded based on severity:
    - CRITICAL: Red
    - WARNING: Yellow
    - INFO: Blue

.PARAMETER PcAddresses
    An array of strings containing the IP addresses or FQDNs of the Prism Central instances
    to query.

.EXAMPLE
    .\Get-NutanixUnresolvedAlerts.ps1 -PcAddresses "pc1.mydomain.com", "10.0.0.100"

.NOTES
    Author: Tomy Carrasco (Generated by Assistant)
    Date: 2025-Oct-21
    Version: 1.2
    - Compatible with PowerShell 5.1 and later.
    - Filters alerts to show only those from source entity type 'cluster'.
    - Ensure network connectivity to the specified Prism Central instances on port 9440.
#>
function Get-NutanixUnresolvedAlerts {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string[]]$PcAddresses
    )

    # --- Script Configuration ---
    $credential = Get-Credential -Message "Enter Nutanix Prism Central Credentials (e.g., admin)"
    $outputFile = "$([Environment]::GetFolderPath('Desktop'))\Nutanix_Unresolved_Alerts.html"
    $allAlerts = @()

    # --- PowerShell 5.1 Compatibility Section ---
    # Force the use of TLS 1.2 for the session.
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

    # Ignore SSL/TLS certificate errors for self-signed certificates.
    add-type @"
    using System.Net;
    using System.Security.Cryptography.X509Certificates;
    public class TrustAllCertsPolicy : ICertificatePolicy {
        public bool CheckValidationResult(ServicePoint srvPoint, X509Certificate certificate, WebRequest request, int certificateProblem) {
            return true;
        }
    }
"@
    [System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy

    # --- Main Processing Loop ---
    foreach ($pc in $PcAddresses) {
        Write-Host "Connecting to Prism Central: $pc"
        $apiUrl = "https://{0}:9440/api/monitoring/v4.0/serviceability/alerts" -f $pc
        $authHeader = "Basic " + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $credential.UserName, $credential.GetNetworkCredential().Password)))

        $headers = @{
            "Authorization" = $authHeader
            "Content-Type"  = "application/json"
        }

        # --- MODIFIED LINE ---
        # The v4 API filter is updated to include 'sourceEntity/type eq 'cluster''
        # This ensures we only get alerts from Prism Element clusters.
        $filter = "?`$filter=isResolved eq false and sourceEntity/type eq 'cluster'&`$expand=sourceEntity"
        $fullUrl = $apiUrl + $filter

        try {
            $response = Invoke-RestMethod -Uri $fullUrl -Method Get -Headers $headers -ErrorAction Stop

            if ($null -ne $response.data) {
                Write-Host "Successfully retrieved $($response.data.Count) unresolved alerts from $pc."
                $response.data | ForEach-Object {
                    $_ | Add-Member -MemberType NoteProperty -Name "PrismCentral" -Value $pc
                    $allAlerts += $_
                }
            } else {
                Write-Host "No unresolved alerts from Prism Element clusters found on $pc."
            }
        }
        catch {
            Write-Warning "Failed to retrieve alerts from $pc. Error: $($_.Exception.Message)"
        }
    }

    # --- HTML Report Generation ---
    if ($allAlerts.Count -gt 0) {
        Write-Host "Generating HTML report..."

        $head = @"
<style>
    body { font-family: 'Segoe UI', Arial, sans-serif; }
    h1, h2 { color: #003366; }
    table { border-collapse: collapse; width: 100%; margin-bottom: 20px; }
    th, td { border: 1px solid #dddddd; text-align: left; padding: 8px; }
    th { background-color: #f2f2f2; }
    .CRITICAL { background-color: #FFBABA; } /* Red */
    .WARNING { background-color: #FFF2BA; } /* Yellow */
    .INFO { background-color: #BAE1FF; } /* Blue */
</style>
"@

        $body = "<h1>Nutanix Unresolved Alerts Report</h1>"
        $body += "<p>Generated on: $(Get-Date)</p>"

        $groupedAlerts = $allAlerts | Group-Object -Property { $_.sourceEntity.name }

        foreach ($group in $groupedAlerts) {
            $clusterName = if ($group.Name) { $group.Name } else { "Unknown Cluster" }
            $body += "<h2>Cluster: $clusterName</h2>"
            $body += "<table>"
            $body += "<tr><th>Severity</th><th>Message</th><th>Source Entity</th><th>Created Time</th><th>Prism Central</th></tr>"

            $sortedGroup = $group.Group | Sort-Object @{Expression={@('CRITICAL', 'WARNING', 'INFO').IndexOf($_.severity)}; Ascending=$true}

            foreach ($alert in $sortedGroup) {
                $severityClass = $alert.severity
                $body += "<tr class='$severityClass'>"
                $body += "<td>$($alert.severity)</td>"
                $body += "<td>$($alert.message)</td>"
                $body += "<td>$($alert.sourceEntity.name) ($($alert.sourceEntity.type))</td>"
                $body += "<td>$($alert.createdTimeStamp)</td>"
                $body += "<td>$($alert.PrismCentral)</td>"
                $body += "</tr>"
            }
            $body += "</table>"
        }

        ConvertTo-Html -Head $head -Body $body | Out-File -FilePath $outputFile
        Write-Host "Report successfully generated at: $outputFile"
    } else {
        Write-Host "No unresolved alerts found across all specified Prism Central instances. No report generated."
    }
}

# --- How to Run the Script ---
# Replace the example IPs with your actual Prism Central IPs or FQDNs
# Example:
# Get-NutanixUnresolvedAlerts -PcAddresses "192.168.1.10", "pc-secondary.corp.local"
